#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running build"
npm run build

# Run linting
echo "🔍 Running ESLint..."
npm run lint

# Run unit tests
echo "🧪 Running unit tests..."
npm run test:unit

echo "✅ Pre-commit checks passed!"
